/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNITest */

#ifndef _Included_JNITest
#define _Included_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNITest
 * Method:    greet
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNITest_greet
  (JNIEnv *, jobject);

/*
 * Class:     JNITest
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JNITest_getString
  (JNIEnv *, jobject);

/*
 * Class:     JNITest
 * Method:    getCurrentThreadCpuTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_JNITest_getCurrentThreadCpuTime
  (JNIEnv *, jobject);

/*
 * Class:     JNITest
 * Method:    getCurrentThreadName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JNITest_getCurrentThreadName
  (JNIEnv *, jobject);

/*
 * Class:     JNITest
 * Method:    printTopMethodOfThreads
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNITest_printTopMethodOfThreads
  (JNIEnv *, jobject);

/*
 * Class:     JNITest
 * Method:    getStringArray
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_JNITest_getStringArray
  (JNIEnv *, jobject);

/*
 * Class:     JNITest
 * Method:    getTopMethods
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_JNITest_getTopMethods
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
