/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class StackTrace */

#ifndef _Included_StackTrace
#define _Included_StackTrace
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     StackTrace
 * Method:    startStackTrace
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_StackTrace_startStackTrace
  (JNIEnv *, jobject);

/*
 * Class:     StackTrace
 * Method:    detectBlackSwan
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_StackTrace_detectBlackSwan
  (JNIEnv *, jobject);

/*
 * Class:     StackTrace
 * Method:    getTopMethods
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_StackTrace_getTopMethods
  (JNIEnv *, jobject);

/*
 * Class:     StackTrace
 * Method:    getCurrentThreadName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_StackTrace_getCurrentThreadName
  (JNIEnv *, jobject);

/*
 * Class:     StackTrace
 * Method:    getThreadCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_StackTrace_getThreadCount
  (JNIEnv *, jobject);

/*
 * Class:     StackTrace
 * Method:    setBuffers
 * Signature: (Ljava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_StackTrace_setBuffers
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
